apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-api
  labels:
    app: employee-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employee-api
  template:
    metadata:
      labels:
        app: employee-api
    spec:
      containers:
        - name: employee-api
          image: himanshu085/employee-api:48   # Make sure this is the correct image
          ports:
            - containerPort: 8080
          env:
            - name: SCYLLA_HOST
              value: "scylla-service"
            - name: SCYLLA_PORT
              value: "9042"
            - name: SCYLLA_KEYSPACE
              value: "employee_db"
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_PORT
              value: "6379"
          readinessProbe:
            httpGet:
              path: /api/v1/employee/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30   
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /api/v1/employee/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 5
