apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-api
  labels:
    app: employee-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employee-api
  template:
    metadata:
      labels:
        app: employee-api
    spec:
      initContainers:
        - name: wait-for-scylla
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z scylla-service 9042; do echo waiting for scylla; sleep 5; done']
        - name: wait-for-redis
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z redis-service 6379; do echo waiting for redis; sleep 5; done']
      containers:
        - name: employee-api
          image: himanshu085/employee-api:48  # Update with correct image tag
          ports:
            - containerPort: 8080
          env:
            - name: SCYLLA_HOST
              value: "scylla-service"
            - name: SCYLLA_PORT
              value: "9042"
            - name: SCYLLA_KEYSPACE
              value: "employee_db"
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_PORT
              value: "6379"
          readinessProbe:
            httpGet:
              path: /api/v1/employee/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /api/v1/employee/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 5
